project_name: gith
version: 2

# Build configuration
builds:
  - id: gith
    binary: gith
    main: ./main.go

    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

# Archive configuration (zip/tar.gz files)
archives:
  - id: gith
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: tar.gz
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - README.md
      - LICENSE

nfpms:
  - id: gith
    package_name: gith
    ids:
      - gith
    vendor: a3chron
    homepage: "https://a3chron.vercel.app/"
    maintainer: "Kurt Schambach <kurt.schambach@gmail.com>"
    description: "TUI git helper"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin

checksum:
  name_template: "checksums.txt"

# GitHub release configuration
release:
  github:
    owner: a3chron
    name: gith

  # Release notes
  header: |
    # Welcome to this new release of gith! 🎉

  footer: |
    **Full Changelog**: https://github.com/a3chron/gith/compare/{{ .PreviousTag }}...{{ .Tag }}

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "Merge pull request"
  groups:
    - title: Features
      regexp: "^feat(\\([a-zA-Z0-9_-]+\\))?(!)?:\\s(.+)"
      order: 0
    - title: Bug fixes
      regexp: "^fix(\\([a-zA-Z0-9_-]+\\))?(!)?:\\s(.+)"
      order: 1
    - title: Others
      order: 999
